### PR TITLE
Fixes for open issues #27,#20,#29

### PR DESCRIPTION
**Pull request by bgulotta**
Added unit testing framework, first passport model test, and updated code so that it passes.

### CODE REVIEW

**Comment by bgulotta** [comment]
Not sure why the Travis CI build failed to find sails. It is working just fine in my environment.

**Comment by tjwebb** [comment]
I can take a look at the tests.

> +#IntelliJ Files

Haha what is this?

**Comment by bgulotta** [comment]
i use intellij ide. just added that to the .gitignore so the files don't get checked in

**Comment by bgulotta** [comment]
I'm also going through the model and controllers and backfill some more tests.

**Comment by bgulotta** [comment]
https://www.jetbrains.com/idea/

awesome ide made by jetbrains

**Comment by jifeon** [comment]
@bgulotta  I think IDE specific files should be ignored globally for all your repos https://help.github.com/articles/ignoring-files/#create-a-global-gitignore It's not good to store it inside local .gitignore but I don't know does it matter for maintainer ))

**Comment by bgulotta** [comment]
thanks @jifeon. let me get that in place so i can remove it from the repositories .gitignore

**Comment by tjwebb** [comment]
I don't care all that much, mostly I found it amusing. 

Overall this PR is fantastic, thank you @bgulotta

**Comment by tjwebb** [comment]
The rest of the project has 2 spaces for tabs, looks like you're using 4. Can you switch two 2 so that it's in style with the rest of the code?

**Comment by bgulotta** [comment]
sure thing

**Comment by bgulotta** [comment]
i just added 2 more unit tests and @dottodot's fixes for issue #28

**Comment by bgulotta** [comment]
done

**Comment by bgulotta** [comment]
Any idea why the node 0.10 is failing in Travis? It's the version I'm on in my development environment.

**Comment by tjwebb** [comment]
Not sure; I'm also not sure why Travis-CI still says the build is "in progress". I'm going to try re-running it

**Comment by bgulotta** [comment]
I was able to reproduce this issue locally. It appears that version of npm used on the 0.10 node build isn't installing the peerDependencies in the package.json. I'm going to see if there is a work around.

**Comment by tjwebb** [comment]
Easy enough. Thanks

**Pull request merged**
