### PR TITLE
Issues/45: implement /user/me route

### LINKED ISSUE #45: How to GET current user?

### PR DESCRIPTION
**Pull request by tjwebb**
- resolves #45

### CODE REVIEW

**Comment by tjwebb** [comment]
@secrettriangle published this feature in 1.2.0

**Comment by secrettriangle** [comment]
I get the same empty response returned when I'm authed and not authed, via both socket and HTTP?

**Comment by tjwebb** [comment]
Any idea why this works? https://github.com/tjwebb/sails-auth/blob/master/test/unit/controllers/UserController.test.js#L20-L35

**Comment by secrettriangle** [comment]
It works with sails-auth alone but sails-permissions it does as I describe. I've created a repo [here](https://github.com/secrettriangle/sails-permissions-test) It's a bare `sails new` project that has completed the sails-permissions README and [added `UserController` to `config/policies.js`](https://github.com/secrettriangle/sails-permissions-test/commit/8b1014ebba47585bdf6231c63eae6fd831e9615a).

To reproduce:

* `POST /register` with `email=admin1@example.com&password=admin1234`
* `POST /auth/local` with `identifier=admin1@example.com&password=admin1234`
* `GET /user/me`

**Comment by secrettriangle** [comment]
The problem is [this line](https://github.com/secrettriangle/sails-permissions-test/commit/8b1014ebba47585bdf6231c63eae6fd831e9615a#diff-1772787522b4524b7adf5cc5533d9616R66). If you change it to say `me: ['passport']` it works. This is strange because according to [sails-auth/config/env/testing.js](https://github.com/tjwebb/sails-auth/blob/master/config/env/testing.js#L29) a specific `UserController.me` policy is not needed. Not yet sure why it's needed with sails-permissions.

**Pull request merged**
